language: rust

os: 
  - linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cd "${TRAVIS_BUILD_DIR}/structural/"

        - MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
        - echo "Installing latest nightly with Miri"
        - echo "$MIRI_NIGHTLY"
        - rustup set profile minimal
        - rustup default "$MIRI_NIGHTLY"
        - rustup override set "$MIRI_NIGHTLY"
        - rustup component add miri
        - cargo miri setup

        - cargo test --no-default-features --features nightly_specialization
        - cargo test --no-default-features --features alloc --features nightly_specialization
        - cargo test --no-default-features --features std nightly_specialization
        
        - cargo test --no-default-features --features nightly_better_macros
        - cargo test --no-default-features --features alloc --features nightly_better_macros
        - cargo test --no-default-features --features std nightly_better_macros
        
        - cargo test --no-default-features --features better_macros
        - cargo test --no-default-features --features alloc --features better_macros
        - cargo test --no-default-features --features std better_macros
        
        - cargo test --all-features
        
        - cargo clean

        # I need to pass each individual feature with --features featurename
        # because otherwise it gets parsed as a test file.
        - cargo miri test --no-default-features --features nightly_specialization -- -- -Zunstable-options --exclude-should-panic
        - cargo miri test --no-default-features --features alloc --features nightly_specialization -- -- -Zunstable-options --exclude-should-panic
        - cargo miri test --no-default-features --features std --features nightly_specialization -- -- -Zunstable-options --exclude-should-panic
        - cargo miri test --all-features -- -- -Zunstable-options --exclude-should-panic

    - rust: 1.34.0

script:
  
  - cd "${TRAVIS_BUILD_DIR}/structural_derive/"
  - cargo test

  - cd "${TRAVIS_BUILD_DIR}/structural/"
  - cargo test
  - cargo test --no-default-features 
  - cargo test --no-default-features --features alloc
