language: rust

os: 
  - linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      script:
        - cd "${TRAVIS_BUILD_DIR}/structural/"

        - MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
        - echo "Installing latest nightly with Miri"
        - echo "$MIRI_NIGHTLY"
        - rustup set profile minimal
        - rustup default "$MIRI_NIGHTLY"
        - rustup override set "$MIRI_NIGHTLY"
        - rustup component add miri
        - cargo miri setup

        - cargo test --no-default-features --features testing --features nightly_specialization
        - cargo test --no-default-features --features testing --features alloc --features nightly_specialization
        - cargo test --no-default-features --features testing --features std nightly_specialization
        
        - cargo test --no-default-features --features testing --features nightly_better_macros
        - cargo test --no-default-features --features testing --features alloc --features nightly_better_macros
        - cargo test --no-default-features --features testing --features std nightly_better_macros
        
        - cargo test --no-default-features --features testing --features better_macros
        - cargo test --no-default-features --features testing --features alloc --features better_macros
        - cargo test --no-default-features --features testing --features std better_macros
        
        - cargo test --no-default-features --features testing --features nightly_impl_fields
        - cargo test --no-default-features --features testing --features alloc --features nightly_impl_fields
        - cargo test --no-default-features --features testing --features std nightly_impl_fields
        
        - cargo test --all-features
        
        - cargo clean

        # I need to pass each individual feature with --features featurename
        # because otherwise it gets parsed as a test file.
        - cargo miri test --no-default-features --features testing --features nightly_specialization
        - cargo miri test --no-default-features --features testing --features alloc --features nightly_specialization
        - cargo miri test --no-default-features --features testing --features std --features nightly_specialization
        - cargo miri test --all-features

    - rust: 1.34.0

script:
  
  - cd "${TRAVIS_BUILD_DIR}/structural_derive/"
  - cargo test --features testing

  - cd "${TRAVIS_BUILD_DIR}/structural/"
  - cargo test --features testing
  - cargo test --no-default-features --features testing  
  - cargo test --no-default-features --features "testing alloc"
