language: rust

os: 
  - linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.34.0

script:
  
  - cd "${TRAVIS_BUILD_DIR}/structural_derive/"
  - cargo test

  - cd "${TRAVIS_BUILD_DIR}/structural/"
  - cargo test
  - cargo test --no-default-features 
  - cargo test --no-default-features --features alloc
