language: rust

os: 
  - linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cd "${TRAVIS_BUILD_DIR}/structural/"

        - MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
        - echo "Installing latest nightly with Miri: $MIRI_NIGHTLY"
        - rustup set profile minimal
        - rustup default "$MIRI_NIGHTLY"
        - rustup component add miri
        - cargo miri setup

        - cargo test --no-default-features --features nightly_specialization
        - cargo +nightly miri test --no-default-features --features nightly_specialization -- -Zunstable-options --exclude-should-panic
        
        - cargo test --no-default-features --features alloc nightly_specialization
        - cargo +nightly miri test --no-default-features --features alloc nightly_specialization -- -Zunstable-options --exclude-should-panic
        
        - cargo test --no-default-features --features std nightly_specialization
        - cargo +nightly miri test --no-default-features --features std nightly_specialization -- -Zunstable-options --exclude-should-panic
    - rust: 1.34.0

script:
  
  - cd "${TRAVIS_BUILD_DIR}/structural_derive/"
  - cargo test

  - cd "${TRAVIS_BUILD_DIR}/structural/"
  - cargo test
  - cargo test --no-default-features 
  - cargo test --no-default-features --features alloc
