[package]
name = "structural_derive"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description="Derives for abstracting over fields."
documentation = "https://docs.rs/structural/"
keywords = ["data-structures"]
categories = ["data-structures","rust-patterns"]
repository = "https://github.com/rodrimati1992/structural_crates/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "../APACHE_license", 
    "../MIT_license"
]

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"

[dependencies.core_extensions]
default_features=false
features=["std"]
version="0.1"

[dependencies.syn]
version = "1.0"
features=["full","extra-traits"]



###### as_derive_utils

[dependencies.as_derive_utils]
version="0.8.1"
#path="../../abi_stable_crates/as_derive_utils"

[dev-dependencies.as_derive_utils]
version="0.8.1"
#path="../../abi_stable_crates/as_derive_utils"
features=["testing"]


